# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from odoo import api, models, modules, fields


class Contacts1Fast(models.Model):
	_name = 'res.partner'
	_inherit = 'res.partner'

	vid = fields.Integer(string="Vid")
	is_contact = fields.Boolean(string='Color Index')
	profile_url = fields.Char(string="profile-url")
	firstname = fields.Text(string="Họ và tên")
	bank_name = fields.Text(string="TK Ngân hàng")
	bank_account = fields.Char(string="STK")
	company = fields.Text(string="Công ty")
	average_salary = fields.Integer(string="Lương trung bình hàng tháng")
	marital_status = fields.Text(string="Tình trạng hôn nhân")
	so_tien_muon_vay_1_5m = fields.Integer(string="số tiền muốn vay")
	salary_statement_file = fields.Char(string="Link file bảng lương")
	createdate = fields.Char(string="Ngày tạo contact")
	hubspot_owner_id = fields.Integer(string="user id hubspot")
	hs_analytics_num_page_views = fields.Integer(string="Số lượt view page")
	id_number = fields.Integer(string="Số CMT/Căn cước/Passport")
	ngh_nghip = fields.Text(string="Nghề nghiệp")
	thu_nhp_hng_thng = fields.Integer(string="Thu nhập hàng tháng")
	phone = fields.Char(string="SĐT")
	gender = fields.Char(string="Giới tính")
	city = fields.Char(string="Thành phố")
	status_td = fields.Text(string="Trạng thái thẩm định")
	date_of_birth = fields.Char(string="Ngày tháng năm sinh")
	anh_chup_so_ho_khau = fields.Char(string="Link ảnh chụp SHK")
	link_facebook = fields.Char(string="Link Facebook")
	address_of_published_id = fields.Text(string="Nơi cấp CMT/Căn cước")
	date_of_published_id = fields.Char(string="Ngày cấp CMT/Căn cước")
	id_and_face_file = fields.Char(string="Link ảnh chụp mặt + CMT")
	current_house = fields.Text(string="Nhà ở hiện tại")
	id_file = fields.Char(string="Link ảnh chụp CMT")
	email = fields.Char(string="Email")
	salary_payment_type = fields.Text(string="Hình thức thanh toán")
	jobtitle = fields.Text(string="Nghề nghiệp")
	phone_number_relationship_01 = fields.Integer(string="SĐT người thân 1")
	phone_number_relationship_02 = fields.Integer(string="SĐT người thân 2")
	detailed_address = fields.Text(string="Địa chỉ chi tiết")
	relationship_01 = fields.Text(string="Mối quan hệ 1")
	relationship_02 = fields.Text(string="Mối quan hệ 2")
	name_relationship_01 = fields.Text(string="Tên người thân 1")
	name_relationship_02 = fields.Text(string="Tên người thân 2")
	a_ch_ni__hin_ti = fields.Text(string="Địa chỉ nơi ở hiện tại")
	tai_lieu_khac = fields.Char(string="Link tài liệu khác")
	muc_thu_nhap_trung_binh_hang_thang = fields.Integer(string="Mức thu nhập hàng tháng")
	user_password = fields.Char(string="user pw")
	user_status = fields.Char(string="Trạng thái user")
	mkt_level = fields.Char(string="Trạng MKT level")
	video_confirmed = fields.Char(string="Link video xác nhận")
	utm_source = fields.Char(string="Nguồn contact")
	backup_salary_statement_file = fields.Char(string="Backup Link file bảng lương")
	backup_anh_chup_so_ho_khau = fields.Char(string="Backup Link ảnh chụp SHK")
	backup_id_and_face_file = fields.Char(string="Backup Link ảnh chụp mặt + CMT")
	backup_id_file = fields.Char(string="Backup Link ảnh chụp CMT")
	backup_tai_lieu_khac = fields.Char(string="Backup Link tài liệu khác")
	backup_video_confirmed = fields.Char(string="Backup Link video xác nhận")